# IMAGEM QUE ESTÁ SENDO UTILIZADA
FROM node:alpine

# CRIA UMA PASTA DENTRO DO CONTAINER 
WORKDIR /usr/app

# COPIA O PACKAGE.JSON
COPY package*.json ./

# INSTALA AS DEPENDÊNCIAS
RUN npm install

# COPIA O RESTANTE DOS ARQUIVOS, EXCETO NODE_MODULES E O QUE ESTIVER DENTRO DO .DOCKERIGNORE
COPY . .

# QUAL PORTA QUEREMOS OUVIR DENTRO DO CONTAINER
EXPOSE 3000
EXPOSE 4000

# COMANDO PRA STARTAR O SERVIDOR // SÓ PODE TER UM CMD POR ARQUIVO
CMD ["npm","start"]